# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100000)),
                ('features', models.CharField(max_length=100000)),
                ('implementation', models.CharField(max_length=100000)),
                ('uml', models.CharField(max_length=100000)),
                ('output', models.CharField(max_length=100000)),
                ('gists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.Gist')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='tags',
            field=models.ManyToManyField(to='patterns.Tag'),
        ),
    ]
