# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='description',
            field=models.CharField(default=None, max_length=100000),
            preserve_default=False,
        ),
    ]
