# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_pattern_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='tags',
        ),
        migrations.AddField(
            model_name='pattern',
            name='tags',
            field=models.ManyToManyField(to='patterns.Tag'),
        ),
    ]
