# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0003_auto_20170329_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='features',
            field=models.CharField(default=None, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='gist',
            field=models.CharField(default=None, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='implementation',
            field=models.CharField(default=None, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pattern',
            name='uml',
            field=models.CharField(default=None, max_length=100000),
            preserve_default=False,
        ),
    ]
