# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_auto_20170418_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100000)),
            ],
        ),
        migrations.AddField(
            model_name='pattern',
            name='output',
            field=models.CharField(default=None, max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pattern',
            name='gist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.Gist'),
        ),
    ]
