# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0006_auto_20170418_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='gist',
            name='name',
            field=models.CharField(default=None, max_length=100000),
            preserve_default=False,
        ),
    ]
